# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Frans Coomans
email:
description: >- # this means to ignore newlines until "baseurl:"
  Personal portfolio of Frans Coomans â€” Offensive Cybersecurity Consultant.
# twitter_username: username
# github_username: username
search: true
search_provider: lunr
search_full_content: true
enable_copy_code_button: true
words_per_minute: 200

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: contrast
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Africa/Johannesburg # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

collections:
  htb-machines:
    output: true
    permalink: /reports/htb/machines/:path/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - assets/css/custom.scss
  - assets/*.md

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  # - jekyll-feed
  - jemoji
  - jekyll-include-cache

# feed:
#   path: /feed.xml
#   posts_limit: 10
#   collections:
#     posts:
#       output: true
#     pages:
#       output: true

author: "Frans Coomans"

footer:
  links:
    - label: "Contact"
      icon: "fas fa-fw fa-envelope-square"
      url: "/contact/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/frans-coomans/"

defaults:
  # labs collection
  - scope:
      path: ""
      type: htb-machines
    values:
      layout: single
      show_date: true
      read_time: true
      toc: true
      toc_sticky: true
      share: true
  # # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

atom_feed:
  hide: true
